//! Upload-and-share — Rust port of the Python `share.py` (header "Share").
//!
//! Share links are presigned GET URLs (S3, SigV4 query auth) or read-only SAS
//! URIs (Azure); OneDrive uploads via Graph and returns a view link. Uploads
//! use a presigned PUT (S3) / write SAS (Azure) so no SDK or header signing
//! is needed. Unit tests pin the signatures against vectors generated by the
//! Python implementation, so the two apps produce identical URLs.

use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};
use wondershot_core::settings::Settings;

type HmacSha256 = Hmac<Sha256>;

const S3_MAX_EXPIRY: u64 = 604_800; // 7 days — SigV4's hard cap
const AZURE_SAS_VERSION: &str = "2021-08-06";

fn hmac_sha256(key: &[u8], msg: &[u8]) -> Vec<u8> {
    let mut mac = HmacSha256::new_from_slice(key).expect("hmac accepts any key length");
    mac.update(msg);
    mac.finalize().into_bytes().to_vec()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Percent-encode like Python's `quote(s, safe=...)`.
fn quote(s: &str, safe: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'_' | b'.' | b'-' | b'~' => {
                out.push(b as char)
            }
            _ if safe.contains(b as char) => out.push(b as char),
            _ => out.push_str(&format!("%{b:02X}")),
        }
    }
    out
}

// -- UTC date formatting (no chrono: one small civil-from-days conversion) ---

/// (year, month, day) from days since the Unix epoch (Howard Hinnant's
/// `civil_from_days`, the standard branchless algorithm).
fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = (if mp < 10 { mp + 3 } else { mp - 9 }) as u32;
    (if m <= 2 { y + 1 } else { y }, m, d)
}

/// Unix seconds → (YYYYMMDD, YYYYMMDD"T"HHMMSS"Z", YYYY-MM-DDTHH:MM:SSZ).
fn utc_stamps(epoch: u64) -> (String, String, String) {
    let days = (epoch / 86_400) as i64;
    let secs = epoch % 86_400;
    let (y, mo, d) = civil_from_days(days);
    let (h, mi, s) = (secs / 3600, (secs % 3600) / 60, secs % 60);
    let datestamp = format!("{y:04}{mo:02}{d:02}");
    let amz = format!("{datestamp}T{h:02}{mi:02}{s:02}Z");
    let iso = format!("{y:04}-{mo:02}-{d:02}T{h:02}:{mi:02}:{s:02}Z");
    (datestamp, amz, iso)
}

fn now_epoch() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

// -- S3 (SigV4 query-string auth) --------------------------------------------

fn sigv4_key(secret: &str, date: &str, region: &str) -> Vec<u8> {
    let k = hmac_sha256(format!("AWS4{secret}").as_bytes(), date.as_bytes());
    let k = hmac_sha256(&k, region.as_bytes());
    let k = hmac_sha256(&k, b"s3");
    hmac_sha256(&k, b"aws4_request")
}

/// Presign an absolute S3 object URL (SigV4 query parameters).
pub fn presign_s3_url(
    url: &str,
    region: &str,
    access_key: &str,
    secret_key: &str,
    method: &str,
    expires: u64,
    now_epoch_s: u64,
) -> String {
    let (datestamp, amz_date, _) = utc_stamps(now_epoch_s);
    let scope = format!("{datestamp}/{region}/s3/aws4_request");

    let rest = url.split_once("://").map(|(_, r)| r).unwrap_or(url);
    let (host, path) = match rest.split_once('/') {
        Some((h, p)) => (h, format!("/{p}")),
        None => (rest, "/".to_string()),
    };

    let params: Vec<(String, String)> = vec![
        ("X-Amz-Algorithm".into(), "AWS4-HMAC-SHA256".into()),
        ("X-Amz-Credential".into(), format!("{access_key}/{scope}")),
        ("X-Amz-Date".into(), amz_date.clone()),
        ("X-Amz-Expires".into(), expires.to_string()),
        ("X-Amz-SignedHeaders".into(), "host".into()),
    ];
    let canonical_query = params
        .iter()
        .map(|(k, v)| format!("{}={}", quote(k, ""), quote(v, "")))
        .collect::<Vec<_>>()
        .join("&");
    let canonical_request = [
        method,
        &quote(&path, "/"),
        &canonical_query,
        &format!("host:{host}"),
        "",
        "host",
        "UNSIGNED-PAYLOAD",
    ]
    .join("\n");
    let string_to_sign = [
        "AWS4-HMAC-SHA256",
        &amz_date,
        &scope,
        &hex(&Sha256::digest(canonical_request.as_bytes())),
    ]
    .join("\n");
    let signature = hex(&hmac_sha256(
        &sigv4_key(secret_key, &datestamp, region),
        string_to_sign.as_bytes(),
    ));
    format!("{url}?{canonical_query}&X-Amz-Signature={signature}")
}

/// Path-style URL — works on AWS and every S3-compatible store.
pub fn s3_object_url(endpoint: &str, bucket: &str, key: &str) -> String {
    format!("{}/{bucket}/{}", endpoint.trim_end_matches('/'), quote(key, "/"))
}

// -- Azure Blob (account-key SAS) ---------------------------------------------

/// Blob URL with a service SAS signed by the account key.
pub fn azure_sas_url(
    account: &str,
    container: &str,
    blob: &str,
    account_key_b64: &str,
    permissions: &str,
    expires_days: u64,
    now_epoch_s: u64,
) -> Result<String, String> {
    use base64::Engine;
    let (_, _, expiry) = utc_stamps(now_epoch_s + expires_days * 86_400);
    let resource = format!("/blob/{account}/{container}/{blob}");
    let string_to_sign = [
        permissions,
        "",
        &expiry,
        &resource,
        "",                // signed identifier
        "",                // IP range
        "https",           // protocol
        AZURE_SAS_VERSION, // sv
        "b",               // resource type: blob
        "",                // snapshot time
        "",                // encryption scope
        "", "", "", "", "", // rscc, rscd, rsce, rscl, rsct
    ]
    .join("\n");
    let key = base64::engine::general_purpose::STANDARD
        .decode(account_key_b64)
        .map_err(|e| format!("invalid Azure account key: {e}"))?;
    let sig = base64::engine::general_purpose::STANDARD
        .encode(hmac_sha256(&key, string_to_sign.as_bytes()));
    let qs = [
        format!("sv={AZURE_SAS_VERSION}"),
        "spr=https".into(),
        format!("se={}", quote(&expiry, "")),
        "sr=b".into(),
        format!("sp={permissions}"),
        format!("sig={}", quote(&sig, "")),
    ]
    .join("&");
    Ok(format!(
        "https://{account}.blob.core.windows.net/{container}/{}?{qs}",
        quote(blob, "/")
    ))
}

// -- upload + share orchestration ----------------------------------------------

fn get(s: &Settings, k: &str) -> String {
    s.extra.get(k).map(|v| v.trim().to_string()).unwrap_or_default()
}

fn s3_configured(s: &Settings) -> bool {
    ["s3_endpoint", "s3_bucket", "s3_access_key", "s3_secret_key"]
        .iter()
        .all(|k| !get(s, k).is_empty())
}

fn azure_configured(s: &Settings) -> bool {
    ["azure_account", "azure_container", "azure_key"]
        .iter()
        .all(|k| !get(s, k).is_empty())
}

fn onedrive_configured() -> bool {
    !crate::graph::connected_account().is_empty()
}

pub fn configured_providers(s: &Settings) -> Vec<&'static str> {
    let mut out = Vec::new();
    if s3_configured(s) {
        out.push("s3");
    }
    if azure_configured(s) {
        out.push("azure");
    }
    if onedrive_configured() {
        out.push("onedrive");
    }
    out
}

/// The provider for one-click share surfaces: the user's default if it's
/// configured, else the first configured one, else "".
pub fn default_provider(s: &Settings) -> String {
    let providers = configured_providers(s);
    if providers.is_empty() {
        return String::new();
    }
    let pref = get(s, "share_provider");
    if providers.contains(&pref.as_str()) {
        pref
    } else {
        providers[0].to_string()
    }
}

fn content_type_of(path: &str) -> &'static str {
    match path.rsplit('.').next().map(|e| e.to_ascii_lowercase()).as_deref() {
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        Some("mp4") | Some("m4v") => "video/mp4",
        Some("webm") => "video/webm",
        Some("mkv") => "video/x-matroska",
        _ => "application/octet-stream",
    }
}

/// PUT a file's bytes to `url` (presigned/SAS — no auth header needed).
fn put_file(url: &str, path: &str, extra: &[(&str, &str)]) -> Result<(), String> {
    let data = std::fs::read(path).map_err(|e| e.to_string())?;
    let mut req = ureq::put(url)
        .timeout(std::time::Duration::from_secs(120))
        .set("Content-Type", content_type_of(path));
    for (k, v) in extra {
        req = req.set(k, v);
    }
    match req.send_bytes(&data) {
        Ok(_) => Ok(()),
        Err(ureq::Error::Status(code, _)) => Err(format!("upload failed: HTTP {code}")),
        Err(e) => Err(format!("upload failed: {e}")),
    }
}

/// Upload `path` via `provider` and return a time-limited share URL.
/// Mirrors the Python `share_file` exactly (same key layout + expiries).
pub fn share_file(s: &Settings, path: &str, provider: &str) -> Result<String, String> {
    let name = std::path::Path::new(path)
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| "capture".into());
    let key = format!("wondershot/{name}");
    let days: u64 = get(s, "share_expiry_days").parse().unwrap_or(7).clamp(1, 7);
    let now = now_epoch();
    match provider {
        "s3" => {
            let url = s3_object_url(&get(s, "s3_endpoint"), &get(s, "s3_bucket"), &key);
            let region = {
                let r = get(s, "s3_region");
                if r.is_empty() { "us-east-1".to_string() } else { r }
            };
            let (ak, sk) = (get(s, "s3_access_key"), get(s, "s3_secret_key"));
            put_file(&presign_s3_url(&url, &region, &ak, &sk, "PUT", 3600, now), path, &[])?;
            Ok(presign_s3_url(&url, &region, &ak, &sk, "GET", (days * 86_400).min(S3_MAX_EXPIRY), now))
        }
        "azure" => {
            let (acct, cont, akey) =
                (get(s, "azure_account"), get(s, "azure_container"), get(s, "azure_key"));
            let upload = azure_sas_url(&acct, &cont, &key, &akey, "cw", 1, now)?;
            put_file(&upload, path, &[("x-ms-blob-type", "BlockBlob")])?;
            azure_sas_url(&acct, &cont, &key, &akey, "r", days, now)
        }
        "onedrive" => crate::graph::share(path, &get(s, "graph_drive_id")),
        other => Err(format!("unknown share provider: {other}")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // 2026-06-10 15:30:45 UTC — the timestamp the Python vectors were
    // generated with (sharevec/share_pure.py run against OG share.py).
    const NOW: u64 = 1_781_105_445;

    #[test]
    fn stamps_match_python() {
        let (d, amz, iso) = utc_stamps(NOW);
        assert_eq!(d, "20260610");
        assert_eq!(amz, "20260610T153045Z");
        assert_eq!(iso, "2026-06-10T15:30:45Z");
    }

    #[test]
    fn object_url_matches_python() {
        assert_eq!(
            s3_object_url("https://s3.example.com", "shots", "wondershot/test image.png"),
            "https://s3.example.com/shots/wondershot/test%20image.png"
        );
    }

    #[test]
    fn presign_get_matches_python_vector() {
        let url = s3_object_url("https://s3.example.com", "shots", "wondershot/test image.png");
        let got = presign_s3_url(&url, "us-east-1", "AKIAEXAMPLE", "secretkey123", "GET", 86_400, NOW);
        assert_eq!(
            got,
            "https://s3.example.com/shots/wondershot/test%20image.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAEXAMPLE%2F20260610%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260610T153045Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=f971cca1f05d6196d82f268d70b8e6f8dc4f7c2a82ea507f02567218a62096d7"
        );
    }

    #[test]
    fn presign_put_matches_python_vector() {
        let url = s3_object_url("https://s3.example.com", "shots", "wondershot/test image.png");
        let got = presign_s3_url(&url, "eu-west-1", "AK2", "sk2", "PUT", 3600, NOW);
        assert!(got.ends_with(
            "&X-Amz-Signature=d0cbe8581fe7cc593e9cd7464722dea271d991fdfde0dd7965c00477b2800f71"
        ));
    }

    #[test]
    fn azure_sas_matches_python_vector() {
        use base64::Engine;
        let key = base64::engine::general_purpose::STANDARD.encode(b"0123456789abcdef0123456789abcdef");
        let got =
            azure_sas_url("acct", "shots", "wondershot/test image.png", &key, "r", 7, NOW).unwrap();
        assert_eq!(
            got,
            "https://acct.blob.core.windows.net/shots/wondershot/test%20image.png?sv=2021-08-06&spr=https&se=2026-06-17T15%3A30%3A45Z&sr=b&sp=r&sig=EDmBv2RXviOAQIDF%2B1cYlkpmOYBOPl49IGwfkD8z5hQ%3D"
        );
    }
}
